;<?php
;die();
;/*
[db]
DRIVER 		= "pdo_mysql"
HOST 		= "localhost"
DBNAME 		= "techo_censo"
USER 		= "root"
PASSWORD 	= "MysqlrooT"
CHARSET 	= "utf8"
PREFIX 		= "tnq_"
SMTP 		="localhost"
PORTNIN 		= "3306"
DBNAMESV		= "cobertura_sv"
USERSV 	= "USR4_coberturasv"
PASSWORDSV 	= "G&8$aj8=qas"
DBNAMEHN		= "cobertura_hn"
USERHN 	= "USR7_coberturahn"
PASSWORDHN 	= "1L/q&adf=yua2"
DBNAMENI		= "cobertura_ni"
USERNI 	= "USR2_coberturani"
PASSWORDNI 	= "a3%7f$py(90?"
DBNAMECR		= "cobertura_cr"
USERCR 	= "USR9_coberturacr"
PASSWORDCR 	= "T5g!9/6?=52"
RUTAGT 	= "/appcorp/public_html/mapa_cobertura"
RUTASV 	= "/appcorpsv/public_html/mapa_cobertura"
RUTAHN 	= "/appcorphn/public_html/mapa_cobertura"
RUTANI 	= "/appcorpni/public_html/mapa_cobertura"
RUTACR 	= "/appcorpcr/public_html/mapa_cobertura"
?>
